name: "Build and deploy"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://haskell:latest
    steps:
    - uses: actions/checkout@v1
    - name: Install pandoc
      run: cabal new-update && cabal new-install pandoc pandoc-citeproc && cabal new-install pandoc-crossref
    - name: Build PDF
      run: make
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "project.pdf"
        target: "~/uploads"
